name: prepare-release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "New release tag to create"
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      output1: ${{ steps.release_commit.outputs.current_ref }}

    steps:
      - uses: actions/checkout@v4
      - run: make go.mk
      - run: |
          git fetch --tags
          git config --global user.email "operation+build@exoscale.ch"
          git config --global user.name "Exoscale"
      - run: "make prepare-release NEW_VERSION=${{ inputs.release-tag }}"
      - id: release_commit
        run: |
          git push
          git push --tags
          CURRENT_REF=$(git log -1 --format='%H')
          echo "current_ref=$CURRENT_REF" >> "$GITHUB_OUTPUT"
        shell: bash

  call-release-workflow:
    needs: prepare-release
    # since the prepare-release job creates a new commit we have to pass the ref of the new commit to the called workflow
    uses: ./.github/workflows/release.yml@${{needs.prepare-release.outputs.current_ref}}
